CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('admin','operator') NOT NULL DEFAULT 'operator',
    failed_login_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
    locked_until DATETIME DEFAULT NULL,
    last_login_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS servers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(100) NOT NULL,
    hostname VARCHAR(255) NOT NULL,
    ssh_port SMALLINT UNSIGNED NOT NULL DEFAULT 22,
    ssh_user VARCHAR(50) NOT NULL DEFAULT 'deploy',
    ssh_key_path VARCHAR(255) NOT NULL,
    php_path VARCHAR(255) NOT NULL DEFAULT '/usr/bin/php',
    wp_cli_path VARCHAR(255) NOT NULL DEFAULT '/usr/local/bin/wp',
    max_parallel TINYINT UNSIGNED NOT NULL DEFAULT 4,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pairing_tokens (
    id CHAR(36) PRIMARY KEY,
    token CHAR(64) NOT NULL UNIQUE,
    server_id INT UNSIGNED DEFAULT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sites (
    id CHAR(36) PRIMARY KEY,
    server_id INT UNSIGNED NOT NULL,
    url VARCHAR(255) NOT NULL UNIQUE,
    label VARCHAR(100) NOT NULL,
    wp_path VARCHAR(255) NOT NULL,
    hmac_secret TEXT NOT NULL,
    status ENUM('active','paused','unreachable','error') NOT NULL DEFAULT 'active',
    wp_version VARCHAR(20) DEFAULT NULL,
    php_version VARCHAR(20) DEFAULT NULL,
    last_heartbeat_at DATETIME DEFAULT NULL,
    registered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS telemetry (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    site_id CHAR(36) NOT NULL,
    payload JSON NOT NULL,
    received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS jobs (
    id CHAR(36) PRIMARY KEY,
    site_id CHAR(36) NOT NULL,
    type VARCHAR(50) NOT NULL,
    params JSON DEFAULT NULL,
    status ENUM('pending','running','completed','failed','cancelled') NOT NULL DEFAULT 'pending',
    priority TINYINT UNSIGNED NOT NULL DEFAULT 5,
    attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts TINYINT UNSIGNED NOT NULL DEFAULT 3,
    scheduled_at DATETIME DEFAULT NULL,
    started_at DATETIME DEFAULT NULL,
    completed_at DATETIME DEFAULT NULL,
    duration_ms INT UNSIGNED DEFAULT NULL,
    output LONGTEXT DEFAULT NULL,
    error_output TEXT DEFAULT NULL,
    created_by VARCHAR(50) NOT NULL DEFAULT 'manual',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS activity_log (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED DEFAULT NULL,
    site_id CHAR(36) DEFAULT NULL,
    action VARCHAR(100) NOT NULL,
    details JSON DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
